### ISSUE TITLE
Ability to reliably run code AFTER all tasks have stopped but BEFORE service is registered as finished.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/async-service#20]
### What is wrong

The previous API this library was based on had a `_cleanup()` method that you could implement that would allow you to implement logic that would run **after** all tasks have been stopped but **before** the service registers as finished.

At present, the `asyncio` service runs all of the background tasks as a `DAG` with the `Service.run()` method at the root of the dag.  Upon cancellation, any background task which is cancelled is guaranteed to have had all of it's children cancelled first.   This means that at the point where the `Service.run()` method is cancelled, it is guaranteed that all other background tasks have completed.  Because of this, the following is a reliable way to run code in the manner specified above.

```python
class MyService(Service):
    async def run(self):
        self.manager.run_task(do_background_thing_a)
        self.manager.run_task(do_background_thing_b)

        try:
            await self.manager.wait_finished()
        finally:
            ...  # do cleanup
```

While this pattern accomplishes the goal, it requires intimate knowledge of how the service lifecycle functions to understand why this works.  Is this ok?

### How can it be fixed.

1. We could just document this well.  Good documentation examples and guides as well as the explanation above to help explain why it works.
2. Create a new API where people can embed this logic.

With respect to option 1: I'm inclined to do it this way to keep the library as simple as possible.  I like that a service is just a function... that you can wrap up in a class **or** put in a plain function and use the `as_service` decorator.

With respect to option 2:  This would be pretty simple to implement.  I see two obvious options.

```python
class MyService(Service):
    async def run(self):
        self.manager.run_task(do_background_thing_a)
        self.manager.run_task(do_background_thing_b)

        await self.manager.wait_finished()

    async def cleanup(self):
            ...  # do whatever cleanup and then re-raise

#
# OR MAYBE....
#

await run_service(service, cleanup_fn=...)
```

Both of these suffer from not having an easy way to get context into how/why the service exited where as the `try/finally` can be implemented as `try/except` or even `if any(sys.exc_info())` to check if an exception is being handled.  In fact, it even allows easy implementation of something like this pattern when it's justified.

```python
class MyService(Service):
    async def run(self):
        self.manager.run_task(do_background_thing_a)
        self.manager.run_task(do_background_thing_b)

        try:
            await self.manager.wait_finished()
        except:
            await self.on_error()
        finally:
            await self.on_exit()
        else:
            await self.on_success()
```

My inclination is to leave it simple and document these patterns well with good examples that are easy to copy/paste from. 

We could even explore a metaclass based solution that keeps the manager unaware of this and implements the pattern above by manipulating the `run` method on class construction.

**Comment by pipermerriam** [comment]
Looking at @ralexstokes issue it appears that the following is needed for this to work correctly in trio.

```python
class MyService(Service):
    async def run(self):
        self.manager.run_task(do_background_thing_a)
        self.manager.run_task(do_background_thing_b)

        try:
            await self.manager.wait_finished()
        finally:
            with trio.CancelScope(shield=True):
                await self.on_exit()
```

Otherwise trio ends up raising another `CancelledError` upon the next `await` call since the current scope has been cancelled.

**Comment by carver** [comment]
:+1: to document the try/finally for now, and add a cleanup feature if we think that approach becomes cumbersome.

**Comment by ralexstokes** [comment]
yeah to chime in i think we can get away w/ just documenting the pattern here.

and thanks @pipermerriam for looking into this! i think especially given that we need some extra infrastructure to handle the `trio` case, its better to just explicitly document for now -- like @carver says if we need to find a more succinct abstraction down the road we can :)
