### ISSUE TITLE
No handling of KeyboardInterrupts in asyncio services

### ISSUE THREAD

**Issue by gsalgado** [ethereum/async-service#62]
When a running service's process gets sent a SIGINT, that will cause a KeyboardInterrupt to be triggered by whatever code is executing at that moment, and that exception goes uncaught, causing the manager's `run()` method to exit without cancelling the service or waiting for its cleanup. Once that happens, any code that calls `await manager.stop()` or `await manager.wait_finished()` will hang forever, obviously. This seems to be the cause of most of the timeout errors we get when shutting down trinity components.

IIUC, one complicating factor here is the fact that the `KeyboardInterrupt` may come from different places, depending on what code is executing at the moment. For example:
  1. Any task started by the service via `run_task()` & co
  2. `AsyncioManager._wait_all_tasks_done()` -- although less likely as it usually yields shortly after being given control
  3. Any `asyncio` APIs

**Comment by gsalgado** [comment]
Another change we should make as part of the fix for this is to either get rid of `run_asyncio_service()` or fix it so that it cancels the manager and awaits for it to be finished when `manager.run()` returns. I say that because we already have a few components (in trinity) using this API and they don't wait for the services to finish after `run_asyncio_service()` returns because it is not obvious they should've done that

**Comment by pipermerriam** [comment]
I believe that we want `run_asyncio_service` to provide a strong guarantee that the service has finished before returning so :+1: to fixing that.

**Comment by gsalgado** [comment]
This is all wrong, actually. A KeyboardInterrupt raised from within a service will propagate until it causes us to exit the `background_asyncio_service()` context, which will call `await manager.stop()` (line 416) while the `run()` method is still running in the background (line 407)

https://github.com/ethereum/async-service/blob/6a7ec8426d680fb6a1b59b2dd58100e30679fd52/async_service/asyncio.py#L396-L416

There's nothing to fix here, then, but for some services we get yet another KeyboardInterrupt, and that's what was preventing them from terminating: https://github.com/ethereum/async-service/pull/64
