### ISSUE TITLE
Need `external_api` decorator for trio service.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/async-service#9]
### What is wrong

We have an `external_api` decorator that can be used within an `asyncio` context.

We need an `external_api` decorator that can be used with in a `trio` context

### How to fix

Either write one that works only in `trio` or better, write one that works in *either* context.

**Comment by pipermerriam** [comment]
Also worth noting that it appears the type hints for the asyncio `external_api` aren't working correctly.

**Comment by gsalgado** [comment]
Fixed in #17
